version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: music-invest-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_invest
    ports:
      - "5432:5432"
    volumes:
      - music-invest-pgdata:/var/lib/postgresql/data

volumes:
  music-invest-pgdata:
